Repository 202212-GIZ-YE-FEW/mad-libs-updated-to-pro, pull requests merged in 2023-01, with the labels that each got.

#12 Add the hotkeys handler for project.
  index.html
  utils.js
Labels: feature

#16 parse the story into Array of Objects and return it
  madlibs.js
Labels: formatting

#17 Add word to pos validation.
  utils.js
Labels: feature

#19 Featuers/live update 9
  .vscode/settings.json
  index.html
  madlibs.js
Labels: feature

#20 Live update changes
  index.html
  madlibs.js
  utils.js
Labels: enhancement, refactoring
